services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: demo_mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "14333:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -No -S localhost -U sa -P ${SA_PASSWORD:-YourStrong!Passw0rd} -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    volumes:
      - ./mssql/backup:/var/opt/mssql/backup
      - ./mssql/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro

  postgres:
    image: postgres:16
    container_name: demo_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=suppliers_replica
    ports:
      - "15433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d suppliers_replica"]
      interval: 10s
      timeout: 5s
      retries: 30

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: demo_pgadmin
    depends_on:
      postgres:
        condition: service_started
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/misc/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  symmetricds:
    image: jumpmind/symmetricds:latest
    container_name: demo_symmetricds
    depends_on:
      mssql:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    ports:
      - "31415:31415"
    volumes:
      - ./symmetricds/engines:/opt/symmetric-ds/engines:ro


